# Generated by Django 4.2.2 on 2023-06-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_menu_dish_alter_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attracs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Ціна')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Атракціони',
                'verbose_name_plural': 'Атракціони',
            },
        ),
    ]
