# Generated by Django 4.2.2 on 2023-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_attracs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.IntegerField(max_length=100, verbose_name='До новини')),
                ('image', models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото до новини',
                'verbose_name_plural': 'Фото до новини',
            },
        ),
        migrations.AlterField(
            model_name='attracs',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
