# Generated by Django 4.2.2 on 2023-07-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_imagetophoto_alter_attracs_image_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageToPhoto',
            new_name='MultipleImage',
        ),
        migrations.RenameField(
            model_name='multipleimage',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='multipleimage',
            old_name='photoid',
            new_name='postid',
        ),
    ]
