# Generated by Django 4.2.2 on 2023-07-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_imagetophoto_multipleimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='postid',
            field=models.CharField(max_length=100, null=True, verbose_name='До новини'),
        ),
    ]
