# Generated by Django 4.2.2 on 2023-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_multipleimagekids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimagekids',
            name='postid',
            field=models.CharField(max_length=100, null=True, verbose_name='До атракціону'),
        ),
    ]
