# Generated by Django 4.2.2 on 2023-07-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_multipleimagekids_postid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImageKids',
        ),
    ]
